#!/bin/bash

if [[ "$UID" != 0 ]]; then
	echo "You must be root to run this script"
	exit 1
fi

# --- The actual service

umask 022

cp bin/vef /usr/local/bin/vef

mkdir /var/lib/vefirewall -p
cp {pkg,}/var/lib/vefirewall/vef-restore
cp {pkg,}/etc/systemd/system/vef.service

systemctl daemon-reload

# --- User-oriented data

# Don't squash sets on update
if [[ ! -d /etc/vefirewall/sets ]] || [[ "$*" =~ --restore-sets ]]; then
	umask 177
	mkdir -p /etc/vefirewall/sets
	cp default-sets/* /etc/vefirewall/sets/ -r
fi

# --- Final help

cat <<'EOF'
Very Easy Firewall is now installed!

Enable auto-restore of rules on startup:

	sudo systemctl enable vef

Adapt a rule set in /etc/vefirewall/sets and then run

	sudo vef apply RULENAME

EOF
