#!/bin/bash

if [[ "$UID" != 0 ]]; then
	echo "You must be root to run this script"
	exit 1
fi

umask 022

cp bin/vef /usr/local/bin/vef
cp {pkg,}/var/lib/vefirewall/vef-restore
cp {pkg,}/etc/systemd/system/vef.service


umask 177
mkdir -p /etc/vefirewall/sets
cp default-sets/* /etc/vefirewall/sets/ -r
