#!/bin/bash

#%include argstore.sh bashout.sh

set -euo pipefail

allargs="$(args_store "$@")"

# ---- TRACK VARS -----

POLICYFILE="$(args_get "$allargs" "-f" 1)"
allargs="$(args_remove "$allargs" "-f" 1)"

#%include filemanip.sh application.sh

